---
- name: 配置服务器
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: 更新dnf缓存
      dnf:
        update_cache: yes

    - name: 安装基础软件包
      dnf:
        name: "{{ item }}"
        state: present
      loop:
        - vim
        - git
        - curl
        - wget
        - htop

    - name: 配置SSH免密登录
      authorized_key:
        user: "{{ ansible_user }}"
        key: "{{ lookup('file', '~/.ssh/sean10_tencent.pub') }}"
        state: present

    - name: 更新SSH配置
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      loop:
        - { regexp: '^PasswordAuthentication', line: 'PasswordAuthentication no' }
        - { regexp: '^PubkeyAuthentication', line: 'PubkeyAuthentication yes' }
      notify: restart sshd

    - name: 本地打包 extra_mnt 目录
      delegate_to: localhost
      command: tar czf /tmp/extra_mnt.tar.gz -C ../extra_mnt .
      args:
        creates: /tmp/extra_mnt.tar.gz

    - name: 创建远程目标目录
      file:
        path: /root
        state: directory
        mode: '0755'

    - name: 传输压缩包到远程服务器
      copy:
        src: /tmp/extra_mnt.tar.gz
        dest: /root/extra_mnt.tar.gz
        mode: '0644'

    - name: 解压文件到远程目标目录
      command: tar xzf /root/extra_mnt.tar.gz -C /root
      args:
        creates: /root/clash-for-linux-backup

    - name: 清理远程压缩包
      file:
        path: /root/extra_mnt.tar.gz
        state: absent

    - name: 清理本地临时压缩包
      delegate_to: localhost
      file:
        path: /tmp/extra_mnt.tar.gz
        state: absent

    - name: 启动 Clash
      shell: cd /root/clash-for-linux-backup && bash start.sh
      args:
        executable: /bin/bash

  handlers:
    - name: restart sshd
      service:
        name: sshd
        state: restarted 