version: '2'
services:

  control_machine:
    ports:
      - 8888:8888/tcp
    image: chusiang/ansible-jupyter

  server1:
    ports:
      - 2221:22/tcp
    image: chusiang/ansible-managed-node

  server2:
    ports:
      - 2223:22/tcp
    image: chusiang/ansible-managed-node

  server3:
    ports:
      - 2222:22/tcp
    image: chusiang/ansible-managed-node
