# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: producer_consumer.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17producer_consumer.proto\x12\x11producer_consumer\x1a\x1bgoogle/protobuf/empty.proto\"\x18\n\nIdResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x32_\n\x17ProducerConsumerService\x12\x44\n\tGetNextId\x12\x16.google.protobuf.Empty\x1a\x1d.producer_consumer.IdResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'producer_consumer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IDRESPONSE']._serialized_start=75
  _globals['_IDRESPONSE']._serialized_end=99
  _globals['_PRODUCERCONSUMERSERVICE']._serialized_start=101
  _globals['_PRODUCERCONSUMERSERVICE']._serialized_end=196
# @@protoc_insertion_point(module_scope)
