# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import producer_consumer_pb2 as producer__consumer__pb2


class ProducerConsumerServiceStub(object):
    """定义服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetNextId = channel.unary_unary(
                '/producer_consumer.ProducerConsumerService/GetNextId',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=producer__consumer__pb2.IdResponse.FromString,
                )


class ProducerConsumerServiceServicer(object):
    """定义服务
    """

    def GetNextId(self, request, context):
        """获取下一个ID的方法
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProducerConsumerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetNextId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNextId,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=producer__consumer__pb2.IdResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'producer_consumer.ProducerConsumerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProducerConsumerService(object):
    """定义服务
    """

    @staticmethod
    def GetNextId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/producer_consumer.ProducerConsumerService/GetNextId',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            producer__consumer__pb2.IdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
